window.siteContent = {
  gallery: {
    targetCount: 50,
    batchSize: 9,
    filters: [
      { id: "all", label: "All" },
      { id: "photo", label: "Photos" },
      { id: "video", label: "Videos" },
      { id: "us", label: "Us" },
      { id: "portraits", label: "Portraits" },
      { id: "mirror", label: "Mirror Days" },
      { id: "dates", label: "Date Nights" },
      { id: "calls", label: "Calls" },
      { id: "milestones", label: "Milestones" }
    ],
    featuredVideoOrder: [
      "media/videos/29.MP4",
      "media/videos/40.MOV",
      "media/videos/42.MOV",
      "media/videos/33.MOV",
      "media/videos/27.MOV",
      "media/videos/31.MOV",
      "media/videos/34.MOV",
      "media/videos/18.MOV",
      "media/videos/23.MOV"
    ],
    items: [
      {
        id: "memory-001",
        type: "image",
        src: "media/photos/15.jpg",
        thumbnail: "media/photos/15.jpg",
        fallback: "assets/memory-dawn.svg",
        alt: "A quiet close-up of the two of you resting together",
        caption: "The kind of closeness that makes everything else go quiet.",
        date: "A quiet night in",
        layout: "feature",
        filters: ["us"]
      },
      {
        id: "memory-002",
        type: "image",
        src: "media/photos/30.jpg",
        thumbnail: "media/photos/30.jpg",
        fallback: "assets/memory-window.svg",
        alt: "Gym mirror selfie with overlaid text",
        caption: "Even the ordinary updates felt worth keeping.",
        date: "Gym time",
        layout: "tall",
        filters: ["mirror"]
      },
      {
        id: "memory-003",
        type: "image",
        src: "media/photos/25.jpg",
        thumbnail: "media/photos/25.jpg",
        fallback: "assets/memory-cafe.svg",
        alt: "Soft portrait in a striped top with warm lighting",
        caption: "One of those portraits that feels calm the second you look at it.",
        date: "A soft evening out",
        layout: "portrait",
        filters: ["portraits", "dates"]
      },
      {
        id: "memory-004",
        type: "image",
        src: "media/photos/51.jpg",
        thumbnail: "media/photos/51.jpg",
        fallback: "assets/memory-film.svg",
        alt: "Getting ready while on a video call",
        caption: "Distance looked gentler whenever getting ready included your face on screen.",
        date: "On call",
        layout: "tall",
        filters: ["calls"]
      },
      {
        id: "memory-005",
        type: "image",
        src: "media/photos/24.jpg",
        thumbnail: "media/photos/24.jpg",
        fallback: "assets/memory-trip.svg",
        alt: "Mirror photo in a striped top",
        caption: "A mirror, a smile, and one more reason to stare a little longer.",
        date: "Getting ready",
        layout: "portrait",
        filters: ["mirror", "dates"]
      },
      {
        id: "memory-006",
        type: "image",
        src: "media/photos/38.jpg",
        thumbnail: "media/photos/38.jpg",
        fallback: "assets/memory-window.svg",
        alt: "Mirror portrait in a fitted black outfit",
        caption: "Confidence looked this effortless.",
        date: "A mirror day",
        layout: "tall",
        filters: ["mirror", "portraits"]
      },
      {
        id: "memory-007",
        type: "image",
        src: "media/photos/21.jpg",
        thumbnail: "media/photos/21.jpg",
        fallback: "assets/memory-window.svg",
        alt: "Mirror selfie in a fitting room wearing a black jacket",
        caption: "Trying things on, still somehow looking like the final answer.",
        date: "Out shopping",
        layout: "portrait",
        filters: ["mirror"]
      },
      {
        id: "memory-008",
        type: "image",
        src: "media/photos/32.jpg",
        thumbnail: "media/photos/32.jpg",
        fallback: "assets/memory-window.svg",
        alt: "Mirror outfit photo with black top and cream trousers",
        caption: "Simple, polished, unforgettable.",
        date: "Before heading out",
        layout: "portrait",
        filters: ["mirror", "portraits"]
      },
      {
        id: "memory-009",
        type: "image",
        src: "media/photos/48.jpg",
        thumbnail: "media/photos/48.jpg",
        fallback: "assets/memory-flowers.svg",
        alt: "Mirror photo with a jacket and heart stickers",
        caption: "Warm layers, soft light, and a little playful drama.",
        date: "Later that day",
        layout: "square",
        filters: ["mirror"]
      },
      {
        id: "memory-010",
        type: "image",
        src: "media/photos/49.jpg",
        thumbnail: "media/photos/49.jpg",
        fallback: "assets/memory-cafe.svg",
        alt: "Portrait in blue scrubs",
        caption: "The future you dreamed about already looked beautiful on you.",
        date: "On shift",
        layout: "portrait",
        filters: ["portraits", "milestones"]
      },
      {
        id: "memory-011",
        type: "image",
        src: "media/photos/43.jpg",
        thumbnail: "media/photos/43.jpg",
        fallback: "assets/memory-flowers.svg",
        alt: "Dinner portrait in burgundy",
        caption: "A dinner table, a blue room, and a face worth building a whole evening around.",
        date: "Dinner out",
        layout: "portrait",
        filters: ["dates", "portraits"]
      },
      {
        id: "memory-012",
        type: "image",
        src: "media/photos/36.jpg",
        thumbnail: "media/photos/36.jpg",
        fallback: "assets/memory-dawn.svg",
        alt: "Close selfie in black with a peace sign",
        caption: "A tiny moment of energy and light.",
        date: "A quick selfie",
        layout: "portrait",
        filters: ["portraits"]
      },
      {
        id: "memory-013",
        type: "image",
        src: "media/photos/50.jpg",
        thumbnail: "media/photos/50.jpg",
        fallback: "assets/memory-flowers.svg",
        alt: "Sunlit portrait with a soft glow",
        caption: "Sunlight did what it could, but you were already glowing.",
        date: "Afternoon light",
        layout: "portrait",
        filters: ["portraits"]
      },
      {
        id: "memory-014",
        type: "image",
        src: "media/photos/39.jpg",
        thumbnail: "media/photos/39.jpg",
        fallback: "assets/memory-trip.svg",
        alt: "A candid moment of the two of you in conversation at dinner",
        caption: "One of those conversations you wish could keep going forever.",
        date: "Dinner for two",
        layout: "wide",
        filters: ["us", "dates"]
      },
      {
        id: "memory-015",
        type: "image",
        src: "media/photos/5.jpg",
        thumbnail: "media/photos/5.jpg",
        fallback: "assets/memory-trip.svg",
        alt: "Candid dinner photo in a peach outfit",
        caption: "Caught in the middle of an ordinary gesture that still feels dear.",
        date: "At the table",
        layout: "tall",
        filters: ["dates"]
      },
      {
        id: "memory-016",
        type: "image",
        src: "media/photos/1.jpg",
        thumbnail: "media/photos/1.jpg",
        fallback: "assets/memory-film.svg",
        alt: "A phone showing a video call while sitting outside",
        caption: "Even across a screen, your smile still changed the whole room.",
        date: "Still connected",
        layout: "square",
        filters: ["calls"]
      },
      {
        id: "memory-017",
        type: "image",
        src: "media/photos/2.jpg",
        thumbnail: "media/photos/2.jpg",
        fallback: "assets/memory-window.svg",
        alt: "A quiet candid from the passenger side of a car",
        caption: "A small in-between moment that somehow says everything.",
        date: "On the way",
        layout: "wide",
        filters: ["us"]
      },
      {
        id: "memory-018",
        type: "image",
        src: "media/photos/13.jpg",
        thumbnail: "media/photos/13.jpg",
        fallback: "assets/memory-trip.svg",
        alt: "Mirror photo with the two of you and a friend",
        caption: "The joy of a day that deserved to be remembered out loud.",
        date: "Partly cloudy",
        layout: "feature",
        filters: ["us", "milestones"]
      },
      {
        id: "memory-019",
        type: "image",
        src: "media/photos/45.jpg",
        thumbnail: "media/photos/45.jpg",
        fallback: "assets/memory-flowers.svg",
        alt: "Portrait in burgundy making a peace sign at dinner",
        caption: "Playful, poised, and impossible not to keep.",
        date: "Dinner out",
        layout: "portrait",
        filters: ["dates", "portraits"]
      },
      {
        id: "memory-020",
        type: "image",
        src: "media/photos/40.jpg",
        thumbnail: "media/photos/40.jpg",
        fallback: "assets/memory-film.svg",
        alt: "A collage celebrating one hundred days together",
        caption: "A whole chapter made visible in one page.",
        date: "100 days",
        layout: "wide",
        filters: ["us", "milestones"]
      },
      {
        id: "memory-021",
        type: "image",
        src: "media/photos/44.jpg",
        thumbnail: "media/photos/44.jpg",
        fallback: "assets/memory-cafe.svg",
        alt: "Seated dinner portrait in burgundy",
        caption: "Elegant in the most effortless way.",
        date: "An evening out",
        layout: "portrait",
        filters: ["dates", "portraits"]
      },
      {
        id: "memory-022",
        type: "image",
        src: "media/photos/47.jpg",
        thumbnail: "media/photos/47.jpg",
        fallback: "assets/memory-flowers.svg",
        alt: "Standing outdoors in a textured pink dress at a formal event",
        caption: "A beautiful day, dressed like it mattered.",
        date: "A special occasion",
        layout: "portrait",
        filters: ["milestones", "portraits"]
      },
      {
        id: "memory-023",
        type: "image",
        src: "media/photos/46.jpg",
        thumbnail: "media/photos/46.jpg",
        fallback: "assets/memory-trip.svg",
        alt: "Portrait in a black dress against a marble wall",
        caption: "One of those looks that deserves its own page.",
        date: "Night out",
        layout: "portrait",
        filters: ["portraits", "dates"]
      },
      {
        id: "memory-024",
        type: "image",
        src: "media/photos/22.jpg",
        thumbnail: "media/photos/22.jpg",
        fallback: "assets/memory-window.svg",
        alt: "A second fitting room mirror photo in the black jacket",
        caption: "The same day, saved again because some moments deserve a second glance.",
        date: "Another fitting room save",
        layout: "portrait",
        filters: ["mirror"]
      },
      {
        id: "memory-025",
        type: "video",
        src: "media/videos/3.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 03",
        caption: "A moving memory from one of our quieter chapters.",
        date: "Clip 03",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-026",
        type: "video",
        src: "media/videos/4.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 04",
        caption: "One of the little clips that kept the feeling alive.",
        date: "Clip 04",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-027",
        type: "video",
        src: "media/videos/6.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 06",
        caption: "The kind of moment a still photo could not hold.",
        date: "Clip 06",
        layout: "square",
        filters: []
      },
      {
        id: "memory-028",
        type: "video",
        src: "media/videos/7.MP4",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 07",
        caption: "A saved piece of us, exactly as it happened.",
        date: "Clip 07",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-029",
        type: "video",
        src: "media/videos/8.MP4",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 08",
        caption: "Short, simple, and still impossible to forget.",
        date: "Clip 08",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-030",
        type: "video",
        src: "media/videos/9.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 09",
        caption: "Another scene from the days we keep returning to.",
        date: "Clip 09",
        layout: "square",
        filters: []
      },
      {
        id: "memory-031",
        type: "video",
        src: "media/videos/10.MP4",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 10",
        caption: "A living memory, kept just as tender as the day itself.",
        date: "Clip 10",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-032",
        type: "video",
        src: "media/videos/11.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 11",
        caption: "A moving memory from one of our quieter chapters.",
        date: "Clip 11",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-033",
        type: "video",
        src: "media/videos/12.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 12",
        caption: "One of the little clips that kept the feeling alive.",
        date: "Clip 12",
        layout: "square",
        filters: []
      },
      {
        id: "memory-034",
        type: "video",
        src: "media/videos/14.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 14",
        caption: "The kind of moment a still photo could not hold.",
        date: "Clip 14",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-035",
        type: "video",
        src: "media/videos/16.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 16",
        caption: "A saved piece of us, exactly as it happened.",
        date: "Clip 16",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-036",
        type: "video",
        src: "media/videos/17.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 17",
        caption: "Short, simple, and still impossible to forget.",
        date: "Clip 17",
        layout: "square",
        filters: []
      },
      {
        id: "memory-037",
        type: "video",
        src: "media/videos/18.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 18",
        caption: "Another scene from the days we keep returning to.",
        date: "Clip 18",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-038",
        type: "video",
        src: "media/videos/19.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 19",
        caption: "A living memory, kept just as tender as the day itself.",
        date: "Clip 19",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-039",
        type: "video",
        src: "media/videos/20.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 20",
        caption: "A moving memory from one of our quieter chapters.",
        date: "Clip 20",
        layout: "square",
        filters: []
      },
      {
        id: "memory-040",
        type: "video",
        src: "media/videos/23.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 23",
        caption: "One of the little clips that kept the feeling alive.",
        date: "Clip 23",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-041",
        type: "video",
        src: "media/videos/26.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 26",
        caption: "The kind of moment a still photo could not hold.",
        date: "Clip 26",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-042",
        type: "video",
        src: "media/videos/27.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 27",
        caption: "A saved piece of us, exactly as it happened.",
        date: "Clip 27",
        layout: "square",
        filters: []
      },
      {
        id: "memory-043",
        type: "video",
        src: "media/videos/28.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 28",
        caption: "Short, simple, and still impossible to forget.",
        date: "Clip 28",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-044",
        type: "video",
        src: "media/videos/29.MP4",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 29",
        caption: "Another scene from the days we keep returning to.",
        date: "Clip 29",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-045",
        type: "video",
        src: "media/videos/31.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 31",
        caption: "A living memory, kept just as tender as the day itself.",
        date: "Clip 31",
        layout: "square",
        filters: []
      },
      {
        id: "memory-046",
        type: "video",
        src: "media/videos/33.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 33",
        caption: "A moving memory from one of our quieter chapters.",
        date: "Clip 33",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-047",
        type: "video",
        src: "media/videos/34.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 34",
        caption: "One of the little clips that kept the feeling alive.",
        date: "Clip 34",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-048",
        type: "video",
        src: "media/videos/35.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 35",
        caption: "The kind of moment a still photo could not hold.",
        date: "Clip 35",
        layout: "square",
        filters: []
      },
      {
        id: "memory-049",
        type: "video",
        src: "media/videos/37.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 37",
        caption: "A saved piece of us, exactly as it happened.",
        date: "Clip 37",
        layout: "tall",
        filters: []
      },
      {
        id: "memory-050",
        type: "video",
        src: "media/videos/40.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 40",
        caption: "Short, simple, and still impossible to forget.",
        date: "Clip 40",
        layout: "portrait",
        filters: []
      },
      {
        id: "memory-051",
        type: "video",
        src: "media/videos/41.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 41",
        caption: "Another scene from the days we keep returning to.",
        date: "Clip 41",
        layout: "square",
        filters: []
      },
      {
        id: "memory-052",
        type: "video",
        src: "media/videos/42.MOV",
        thumbnail: "assets/memory-film.svg",
        poster: "assets/memory-film.svg",
        fallback: "assets/memory-film.svg",
        alt: "Video memory 42",
        caption: "A living memory, kept just as tender as the day itself.",
        date: "Clip 42",
        layout: "tall",
        filters: []
      }
    ]
  }
};
